"""Add relationships to Author and Book models

Revision ID: 8bac5ed84976
Revises: b175eacc3bcb
Create Date: 2024-06-28 12:23:11.187795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bac5ed84976'
down_revision: Union[str, None] = 'b175eacc3bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
